### ISSUE TITLE
Split address confirmation and address retrieval

### ISSUE THREAD

**Issue by faboweb** [cosmos/ledger-cosmos-js#10]
Currently the function `getAddressAndPubKey` triggers the address confirmation. This doesn't work well as in a UI at that point you can't show the address so the user can compare against the ledger.
Proposal: `getAddressAndPubKey` doesn't trigger the confirmation. A new function `confirmAddress` triggers the confirmation screen.

**Comment by jleni** [comment]
Yes, at the moment, you would need to call the old `publicKey` and construct the bech32 on the caller side to obtain the address.

To avoid changing current API, how about what exists in gaiaCLI: `getAddressAndPubKeyUnsafe` where you can get both address and pubkey without a confirmation?

**Comment by faboweb** [comment]
Sounds good. I am currently doing it like you proposed so it is not critical.

**Comment by ftheirs** [comment]
Currently we have two methods for this:
- **getAddressAndPubKey**: retrieve the data without user confirmation
- **showAddressAndPubKey**: show info in device and let the user confirm or reject that
