### ISSUE TITLE
New command to list all installed apps

### ISSUE THREAD

**Issue by jleni** [cosmos/ledger-cosmos-js#11]
Add a new command to list all installed apps

**Comment by jleni** [comment]
@faboweb @jbibla 

This command will have some restrictions:
- It will trigger a confirmation "Allow unknown manager" that users may perceive as a security risk
- It can only be called from the Dashboard.

I wonder if these restrictions still makes the command useful and acceptable for your use case.

**Comment by jbibla** [comment]
our intention was for this to be a simple check for the presence of the cosmos app. if there is an extra step i'm not sure it will be worth it.

**Comment by jleni** [comment]
yes, unfortunately checking that an app is installed triggers a security warning/confirmation..

**Comment by jbibla** [comment]
ok. unless fabo objects, i would say this will not be useful for us.

**Comment by jleni** [comment]
ok, I will wait for @faboweb 's opinion and maybe close the ticket then

**Comment by faboweb** [comment]
Thank you Juan as always for putting in the work and trying this out. Much appreciated. But I agree with Jordan that a security warning might be scary to the users. What do you think?

**Comment by jleni** [comment]
Yes, I completely agree. A wallet using this functionality is not a good idea.
Also, once access is allowed, the app would be able to uninstall, replace, etc. resulting in possible security issues.
I will then close this issue, feel free to reopen or revisit this any time.
