### ISSUE TITLE
In the ledger-cosmos-js application Ledger Nano S is not detected in Windows 10!!

### ISSUE THREAD

**Issue by apatifirstblood** [cosmos/ledger-cosmos-js#15]
We ran an application https://github.com/cosmos/ledger-cosmos-js.git in ubuntu and the ledger interaction worked fine.But when we are running the same application in Windows 10 it is not detecting the ledger device and when we checked in console it shows "Transport not defined". The transport is properly defined and thats' why its working properly in Ubuntu..Why is the issue with Window 10.

We have already tested connection using ledger live.Its fine.
We have already tried troubleshooting from https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues. Still no help.

Need assistance urgently.

**Comment by jleni** [comment]
Windows 10 May update complicated things quite a bit (U2F has problems, WebUSB does not work).

Right now, the best option for Windows is to use WebHID. Unfortunately, WebHID support is still experimental, so you will need to manual enable it in Chrome. chrome://flags/#enable-experimental-web-platform-features


What a look at the discussion here: https://github.com/cosmos/ledger-cosmos/issues/157

**Comment by jleni** [comment]
Btw, Ledger Live is a desktop app, so it is using a different kind of transport that is not available in browsers. Desktop vs browser connections are not comparable.

I will close for now as this is a known issue that has already a well documented solution.
Feel free to reopen if this is something substantially different. 
In that case, it would help if you can provide more context.

**Comment by apatifirstblood** [comment]
@jleni thanks u for ur active response.I tried even after enabling experimental-web-platform-features..still the app is not detecting the Ledger Nano S.How shall i proceed now?
