### ISSUE TITLE
Nano X - App Version is not supported

### ISSUE THREAD

**Issue by yuzhiyou1990** [cosmos/ledger-cosmos-js#19]
Error:
{return_code: 25600, error_message: "App Version is not supported"}

Browser:
Chrome

Ledger Cosmos App: 
v2.16.1

Code:
```javascript
import TransportU2F from "@ledgerhq/hw-transport-u2f";

const transport = await TransportU2F.create();
const app = new CosmosApp(transport);
const response = await app.getAddressAndPubKey([44, 118, 5, 0, 3], "cosmos");

```

**Comment by jleni** [comment]
Thanks! We will check it.
Still, I would recommend avoiding U2F and using WebUSB instead.
https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/

**Comment by yuzhiyou1990** [comment]
> Thanks! We will check it.
> Still, I would recommend avoiding U2F and using WebUSB instead.
> https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/


I hope to fix this problem.

For some reasons, only u2f can be used.

**Comment by jleni** [comment]
While we will check why you get this "app version not supported" error... 

Unfortunately, U2F is something that is considered obsolete and it will not be supported in the future. Ledger will not maintain the interface and we U2F is being disabled in most apps. You need to move over to HID, WebUSB or WebHID as soon as possible.
