### ISSUE TITLE
Feature request: Get Ledger firmware

### ISSUE THREAD

**Issue by faboweb** [cosmos/ledger-cosmos-js#7]
In the past we had users reporting an issue "Output buffer too small" which came from an outdated Ledger firmware. To prevent this I would like to query the devices firmware.

**Comment by jleni** [comment]
Ledger devices and the library already supports querying the device firmware version.  Unfortunately, this command is only available when the device is in the dashboard. It is possible that Ledger introduces this feature too all apps in the future.

In the meantime, the only way to achieve this is to add support for this feature directly in the Cosmos app. I am opening an issue in the cosmos app repo to track progress there.

**Comment by faboweb** [comment]
I think that would be best. I don't think this good UX to first direct the user to the main screen wait till the version check is done and then direct him to the cosmos app.

**Comment by jleni** [comment]
no, definitely

**Comment by ftheirs** [comment]
This cannot be implemented due to a limitation from Ledger. Firmware info can be retrieved only in dashboard.

**Comment by chcmedeiros** [comment]
Hey @faboweb! In the latest cosmos-js version, there is already available a method to query firmware info (secure element and mcu version) called deviceInfo(). 
Also, you can find a usage example [here](https://github.com/cosmos/ledger-cosmos-js/blob/958c63a11b4984b5a72e0964d90cf022dce4264b/tests/basic_integration.test.ts#L121)

**Comment by faboweb** [comment]
This issue is from 5 years ago. But appreciate the update
