### ISSUE TITLE
Ledger hangs in address confirmation screen

### ISSUE THREAD

**Issue by faboweb** [cosmos/ledger-cosmos-js#9]
If I trigger the address confirmation and the Ledger goes into screensaver mode. After it wakes up again, it is not responsive.

**Comment by jleni** [comment]
This will require a change in the app itself. Linking to a ticket to the corresponding repo.

**Comment by jleni** [comment]
There has been significant changes in v1.5.1 and this issue does not seem to be reproducible in this new release. I will keep the bug open so we can review the fix once this new version is published.

**Comment by jleni** [comment]
@faboweb is this something that is worth keeping open?
I could never reproduce in the old version and the code for this feature has drastically changed.
